# -*- coding: utf-8 -*-
"""SimpleLR(11-09-22).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlEzot138R71RtD1MrS60Fh2VtpHHUAz
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Gluecose-Level-Age.csv')

df

df.shape

x = df[['Age']]
y = df['Gluecose-level']

x

y

from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=.30, random_state=1)

xtrain

xtest

ytest

from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(xtrain, ytrain)

reg.predict(xtest)

ytest

reg.predict([[55]])

#Manual Calculation
#First write the equation y=mx+c

reg.coef_

reg.intercept_

y = -0.16683831 * 59 + 93.88362512873326

y

